name: test
on:
  push:
  pull_request:

jobs:
  test:
    name: Test ${{ matrix.os }} ${{ matrix.node-version }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [16.x, 18.x]
    runs-on: ${{ matrix.os }}
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: "${{ matrix.node-version }}"
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test:generate-report
      - run: cat test-report.md | tee -a $GITHUB_STEP_SUMMARY
        if: always()
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
